language: php
php:
- 7.2
- 7.3
before_script:
- cp .env.travis .env
- travis_retry composer self-update
- travis_retry composer install --prefer-source --no-interaction
before_install:
- mysql -e 'CREATE DATABASE safeurls_test;'
script:
- vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
services:
- mysql
notifications:
  email: false
env:
  global:
  - USE_NETWORK=true
  - GOOGLE_CLIENT_ID=rattfieldnz-safeurls
  - GOOGLE_CLIENT_VERSION=1.0
  - GOOGLE_CURL_TIMEOUT=10
  - secure: n1NSe5uEIO8qfKnVJfkaH2icc/lnwkwT7VG2dd/4zNTCot5iT5mqWEgDBARSbrl+aiMYBf+fROflgvNEtHU0OcyQzV7aLsyUw8syc/FOF6HXB3zCUwMlpoZZa2dtsZ5t1fWQRwNCOkfDj02Rw4VRUQaOcz2lDZqv9S88JihkHL8juWzKo0FUI5YWxTZzZ4cZ7kY3m9u/Tzng+/J27HkIhABpVzxO2OuHHwXOXztXCt2SkLLbGAdPsHJsP7eRszR4XOUqraKhFBJl/VOlnHn2Z+FuOzCtUBbqaVifOoiDrBKXiOiaRsCemA8lNM7ei6NFKelaT3qVvNcE3cm+BlpHu0vMGeqnpH5Ndjs02XLG4A0u9J7zKx8QDzkVZm3R49kz8t+6kpiXXQfL1dPwJLNDkEp0wd+Pmthb1gBabqJERpFRJh2Xh6POUuM8g4/DFOhtUDgg38ZYyLjTQThIyg/VJ1x0/SDvEeuTPUEynIFunFSGJBADqu0P5+vcVUlImYPnrJgbgdNfyifjik97JNPKakHlWAdedEqPBQwe3mi7xLAQfD0Hxj2VsO4LzVna9d1MaThRmaDj+C16TJhYxB1f3/IYecqc1ldn2j8R6nCWcct+5TzhHFqJR9gtnpUr0XuA3voZRCuRMUfA5QmR+1y2W5FRnavH59pR7d04cWZuYJA=
  matrix:
  - USE_NETWORK=true
  - GOOGLE_CLIENT_ID=rattfieldnz-safeurls
  - GOOGLE_CLIENT_VERSION=1.0
  - GOOGLE_CURL_TIMEOUT=10
  - secure: jEwxD10SGuU4ea85i4TVtfaUo2To62hSBYSTP1sGIRuFdzSNXofHmFdvrNJoP8e7GrXM+SMrLEy93ZMpgdH5dnfk0/YNEx0GaabeUYcnl484eTWBoMMhYmCPc8lwAmIcywX941AyOjgJIqiumxNcGx8JrFPWjhRmsiR31FSzzNpr8bC4y7k+pxpVLfrraESMckoCIk8fUPjuFhXlNtP8cfKA0+9Q9Cl+g90nnNtTigNhmisJCkUdsIAU/xE+4lghcME9z4YSoM49yTFBsUQfOZvkRFiVypz/iMHg6Y/t3fivve7iEl6A1DG+1O5gD7UJE9nWv6ZapMR0ZFmRaFKxurD2/IPrB3JdBiWMAIi5EnulxegmnZmDGaOWke/L4MExfqGsa2Jxk/leO/0RgtvqXjIT/ZPFwRMNA1WgbWGvoKHOxhiTgnYvE0UXbcn3HZL+/0ruswnActScXuWOasefrLtJZBUZIW+P+qipOgqbi4L3zxead4PX4iSG0yiyzwm8Nw+8c5W+P4qzWtLY7OIWoWH1xg/8Q87YhoL+H7M3Qp9XDCemXEopLs6sisfAU8+btSZUmjIE7kVsRGOPgkE5fToeMUZLskeK+/iSFZSBHNGtN7N3S+anpN9ZfYykgydRCNlO7YMAa9c/GHd9ldmMLy37KvncttSnlPvKdxT06yw=
