# PhpUnitGen configuration

# Erase old target files with new one
overwrite: false
# If overwrite is enabled, set to true to backup erased files
backup: false
# If you want to generate tests for Interface too
interface: false
# If you want to generate tests skeleton for protected / private methods
private: true
# Automatically generate tests for getter / setter method
auto: true
# Ignore errors that can be ignored
ignore: true
# Regex (/.*safe-urls.php/ for example) that files must not match to have a tests generation
exclude: '/^.*config\.php$/'
# Regex (/.*.php/ for example) that files should match to have a tests generation
include: '/^.*\.php$/'
# Directories to generate tests for
dirs:
  "src": "tests"
# Files to generate tests for
files:
#  "source/file/to/parse": "target/file/to/put/generated/file"
# Phpdoc annotations to add on the unit tests class header
phpdoc:
  "author": "Rob Attfield <emailme@robertattfield.com>."
  "copyright": "2019 Rob Attfield <emailme@robertattfield.com>."
  "license": "https://opensource.org/licenses/MIT The MIT license."
  "link": "https://github.com/rattfieldnz/safe-urls"
  "since": "File available since Release 0.0.14"